import ollama
import json
import os
from datetime import datetime

# --- Helper Functions ---

def setup_session():
    """Creates a new session directory and returns its path and the paths for log files."""
    os.makedirs("sessions", exist_ok=True)
    session_timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    session_dir = os.path.join("sessions", session_timestamp)
    os.makedirs(session_dir, exist_ok=True)
    paths = {
        'agent1_prompts': os.path.join(session_dir, 'agent1_prompts.json'),
        'agent2_prompts': os.path.join(session_dir, 'agent2_prompts.json'),
        'conversation_log': os.path.join(session_dir, 'conversation_log.json'),
        'plan': os.path.join(session_dir, 'master_plan.txt')
    }
    return session_dir, paths

def save_system_prompt(new_prompt, history_file_path):
    """Appends a new system prompt with a timestamp to its history file."""
    history = []
    if os.path.exists(history_file_path) and os.path.getsize(history_file_path) > 0:
        try:
            with open(history_file_path, 'r', encoding='utf-8') as f:
                history = json.load(f)
                if not isinstance(history, list): history = []
        except (json.JSONDecodeError, IOError):
            history = []
    new_entry = {"timestamp": datetime.now().isoformat(), "system_prompt": new_prompt}
    history.append(new_entry)
    with open(history_file_path, 'w', encoding='utf-8') as f:
        json.dump(history, f, indent=2)

def log_conversation_turn(log_path, agent_name, message, active_prompt):
    """Logs a single turn of the conversation to the main log file."""
    print(f"📝 Logging {agent_name}'s turn...")
    history = []
    if os.path.exists(log_path) and os.path.getsize(log_path) > 0:
        try:
            with open(log_path, 'r', encoding='utf-8') as f:
                history = json.load(f)
                if not isinstance(history, list): history = []
        except (json.JSONDecodeError, IOError):
            history = []
    new_turn = {"timestamp": datetime.now().isoformat(), "agent": agent_name, "active_system_prompt": active_prompt, "message": message}
    history.append(new_turn)
    with open(log_path, 'w', encoding='utf-8') as f:
        json.dump(history, f, indent=2)
    print("✅ Turn logged successfully.")

def create_initial_plan(initial_task, model_name):
    """Calls an LLM to generate a strategic, multi-step plan for the agents."""
    print("🧠 Generating a strategic plan...")
    plan_generation_prompt = (
        f"A user wants two AI agents (an Artist and a Director) to collaborate on this task: '{initial_task}'. "
        f"Create a clear, multi-step plan for them to follow. The plan should be a numbered list of phases. "
        f"Output ONLY the raw text of the plan. Do not add any preamble."
    )
    response = ollama.chat(model=model_name, messages=[{'role': 'user', 'content': plan_generation_prompt}])
    return response['message']['content'].strip()

def create_final_report(session_dir, model_name, initial_task):
    """Spawns a finalizer agent to read all logs and generate a single, high-quality HTML report."""
    print("\n" + "#"*20 + " PHASE 3: FINAL REPORT " + "#"*20)
    print("🤖 Spawning Finalizer Agent to compile results...")
    try:
        with open(os.path.join(session_dir, 'master_plan.txt'), 'r', encoding='utf-8') as f:
            master_plan = f.read()
        with open(os.path.join(session_dir, 'conversation_log.json'), 'r', encoding='utf-8') as f:
            conversation_log = json.dumps(json.load(f), indent=2)

        # A more flexible, guided prompt for the finalizer.
        finalizer_prompt = f"""
You are a professional report generator. Your task is to synthesize a project's data into a polished, dark-themed, single-file HTML report that comprehensively fulfills the original task.

**Project Data:**
1.  **Initial Task:** "{initial_task}"
2.  **Master Plan:**
{master_plan}
3.  **Full Conversation Log:**
{conversation_log}

**Your Instructions:**
1.  Read all the provided data to fully understand the project's goals and execution.
2.  Your main goal is to create a comprehensive final document that fulfills the original task using the content from the conversation log.
3.  Structure the report logically. Start with the Master Plan.
4.  After the plan, create the main body of the report. The structure of this output **must follow the master plan**. For example, if the plan was to write a 10-chapter story, create a heading for each chapter and fill it with the final story text generated by the agents.
5.  Extract only the final, polished creative content from the conversation log. **Do not include director's notes, requests for changes, conversational filler, or JSON instructions.** Present only the final creative output as a finished piece.
6.  Generate a complete, self-contained HTML file using the provided CSS template. Populate the HTML with the synthesized content.

**Output ONLY the raw HTML code.** Start with `<!DOCTYPE html>`.

**HTML Template to Use:**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Report: {initial_task}</title>
    <style>
        :root {{
            --bg-color: #1a1a1a;
            --text-color: #e0e0e0;
            --primary-color: #8a2be2;
            --card-bg: #2c2c2c;
            --border-color: #444;
            --header-font: 'Georgia', serif;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
            margin: 0;
            padding: 2rem;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
        }}
        h1, h2, h3 {{
            color: var(--primary-color);
            font-family: var(--header-font);
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 0.5rem;
        }}
        h1 {{ text-align: center; font-size: 2.5rem; border-bottom: none; }}
        .card {{
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 2rem;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        }}
        pre {{
            background-color: #111;
            padding: 1rem;
            border-radius: 5px;
            white-space: pre-wrap;
            word-wrap: break-word;
            font-family: 'Courier New', Courier, monospace;
        }}
        ul {{ list-style-type: square; padding-left: 20px; }}
        strong {{ color: var(--primary-color); }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Project Report: {initial_task}</h1>
        
        <div class="card">
            <h2>Master Plan</h2>
            <pre>{master_plan}</pre>
        </div>

        <!-- 
        LLM: From here, generate the main body of the report.
        Based on the Master Plan and the Conversation Log, create a series of 'card' divs.
        Each card should represent a major part of the final product as outlined in the plan (e.g., a story chapter, a character profile, a world-building element).
        Use <h2> or <h3> tags for the title of each section inside the card.
        Use <p> tags for the text content.
        
        Example for a story:
        <div class="card">
            <h2>Chapter 1: The Beginning</h2>
            <p>Once upon a time...</p>
        </div>
        <div class="card">
            <h2>Chapter 2: The Journey</h2>
            <p>The hero traveled far and wide...</p>
        </div>

        Now, generate the full report based on the project's actual content and plan.
        -->

    </div>
</body>
</html>
```
"""
        response = ollama.chat(model=model_name, messages=[{'role': 'user', 'content': finalizer_prompt}])
        html_content = response['message']['content'].strip()
        
        # Save the raw HTML response to a debug file
        raw_html_path = os.path.join(session_dir, 'raw_final_report_response.txt')
        with open(raw_html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"📄 Raw HTML response saved to: {raw_html_path}")

        if "```html" in html_content:
            html_content = html_content.split("```html")[1].strip()
        if "```" in html_content:
            html_content = html_content.split("```")[0].strip()
        
        report_path = os.path.join(session_dir, 'final_report.html')
        with open(report_path, 'w', encoding='utf-8') as f: f.write(html_content)
        print(f"✅ Final report successfully generated at: {report_path}")

    except Exception as e:
        print(f"❌ Error during final report generation: {e}")

def extract_json_from_response(response_text):
    """Attempts to extract a JSON object from a response text."""
    try:
        return json.loads(response_text)
    except json.JSONDecodeError:
        return None

# --- Main Application Logic ---
def main():
    """Orchestrates a Director/Artist conversation and generates a final report."""
    MAX_ROUNDS = 20
    MODEL_NAME = 'hf.co/mlabonne/gemma-3-27b-it-abliterated-GGUF:Q8_0'

    session_dir, paths = setup_session()
    agent1_prompts_path = paths['agent1_prompts']
    agent2_prompts_path = paths['agent2_prompts']
    conversation_log_path = paths['conversation_log']
    plan_path = paths['plan']
    
    print("🤖 Director/Artist Conversation System Initialized 🤖")
    print(f"✅ Session logs will be saved to: {session_dir}")
    initial_task = input("Please provide the initial task or topic for the agents: ")

    master_plan = create_initial_plan(initial_task, MODEL_NAME)
    with open(plan_path, 'w', encoding='utf-8') as f: f.write(master_plan)
    print("\n" + "!"*20 + " MASTER PLAN ESTABLISHED " + "!"*20 + "\n" + master_plan + "\n" + "!"*62 + "\n")
    
    conversation_history, last_message = [], ""
    
    try:
        for i in range(MAX_ROUNDS * 2):
            is_artist_turn = i % 2 == 0
            current_agent_name = "Agent 1 (Artist)" if is_artist_turn else "Agent 2 (Director)"
            current_prompt_path = agent1_prompts_path if is_artist_turn else agent2_prompts_path

            print("\n" + "="*20 + f" Turn {i+1}: {current_agent_name}'s Turn " + "="*20)
            print(f"🤔 Generating new persona for {current_agent_name}...")
            
            if is_artist_turn:
                instruction = initial_task
                if i > 0: # If it's not the first turn, try to get the next task from the Director
                    director_feedback = extract_json_from_response(last_message)
                    if director_feedback and 'next_task' in director_feedback:
                        instruction = director_feedback['next_task']
                    else:
                        # Fallback if JSON fails: keep the artist on track
                        print("⚠️ Director's response was not valid JSON. Using a fallback instruction.")
                        instruction = "The Director's last instruction was unclear. Please continue working on the project based on your last submission and the Master Plan."
                
                meta_prompt = (
                    f"Create a system prompt for an AI Artist. The Director has issued this task: '{instruction}'. "
                    f"The prompt must instruct the Artist to creatively fulfill this specific task. "
                    f"Output ONLY the raw text for the system prompt."
                )
            else: # Director's Turn
                meta_prompt = (
                    f"Create a system prompt for an AI Director. The Director's job is to manage the Artist. "
                    f"The Master Plan is:\n{master_plan}\n\nThe Artist just submitted:\n'{last_message}'\n\n"
                    f"The prompt must instruct the Director to output a JSON object with two keys: 'approval_notes' (a brief, 1-sentence approval) and 'next_task' (the single next task from the Master Plan). "
                    f"The Director MUST NOT add creative ideas or conversational fluff. Its output must be ONLY the raw JSON object."
                )

            meta_response = ollama.chat(model=MODEL_NAME, messages=[{'role': 'user', 'content': meta_prompt}])
            new_system_prompt = meta_response['message']['content'].strip().strip('"')
            save_system_prompt(new_system_prompt, current_prompt_path)
            print(f"💡 New Persona: \"{new_system_prompt[:90]}...\"")

            print(f"🗣️  {current_agent_name} is generating its response...")
            messages_for_ollama = [{'role': 'system', 'content': new_system_prompt}]
            messages_for_ollama.extend(conversation_history)
            
            if is_artist_turn:
                final_directive = "You are the Artist. Begin work on the first step of the Master Plan." if i == 0 else "You are the Artist. Your Director has given you a task. Execute it now."
            else:
                final_directive = "You are the Director. The Artist's submission is above. Your entire response must be a single, valid JSON object containing your approval and the next task from the plan."
            messages_for_ollama.append({'role': 'user', 'content': final_directive})
            
            response = ollama.chat(model=MODEL_NAME, messages=messages_for_ollama)
            agent_message = response['message']['content']

            print(f"\n--- {current_agent_name}'s Response ---")
            print(agent_message)
            print("--- End of Response ---")

            last_message = agent_message
            conversation_history.append({'role': 'assistant', 'content': f"[{current_agent_name}]: {agent_message}"})
            log_conversation_turn(conversation_log_path, current_agent_name, agent_message, new_system_prompt)

    except KeyboardInterrupt:
        print("\nConversation interrupted by user.")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")
    
    create_final_report(session_dir, MODEL_NAME, initial_task)
    print("\n✅ Conversation finished. All logs and final report saved.")

if __name__ == "__main__":
    main()